/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsuariosRouteImport } from './routes/_app.usuarios'
import { Route as AppReportesRouteImport } from './routes/_app.reportes'
import { Route as AppPerfilRouteImport } from './routes/_app.perfil'
import { Route as AppNotificacionesRouteImport } from './routes/_app.notificaciones'
import { Route as AppMapaRouteImport } from './routes/_app.mapa'
import { Route as AppFormulariosRouteImport } from './routes/_app.formularios'
import { Route as AppContribuyentesRouteImport } from './routes/_app.contribuyentes'
import { Route as AppAuditoriaRouteImport } from './routes/_app.auditoria'
import { Route as AppNotificacionesIndexRouteImport } from './routes/_app.notificaciones.index'
import { Route as AppFormulariosIndexRouteImport } from './routes/_app.formularios.index'
import { Route as AppContribuyentesIndexRouteImport } from './routes/_app.contribuyentes.index'
import { Route as AppNotificacionesIdRouteImport } from './routes/_app.notificaciones.$id'
import { Route as AppFormulariosIdRouteImport } from './routes/_app.formularios.$id'
import { Route as AppContribuyentesIdRouteImport } from './routes/_app.contribuyentes.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppReportesRoute = AppReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificacionesRoute = AppNotificacionesRouteImport.update({
  id: '/notificaciones',
  path: '/notificaciones',
  getParentRoute: () => AppRoute,
} as any)
const AppMapaRoute = AppMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => AppRoute,
} as any)
const AppFormulariosRoute = AppFormulariosRouteImport.update({
  id: '/formularios',
  path: '/formularios',
  getParentRoute: () => AppRoute,
} as any)
const AppContribuyentesRoute = AppContribuyentesRouteImport.update({
  id: '/contribuyentes',
  path: '/contribuyentes',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditoriaRoute = AppAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificacionesIndexRoute = AppNotificacionesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppNotificacionesRoute,
} as any)
const AppFormulariosIndexRoute = AppFormulariosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppFormulariosRoute,
} as any)
const AppContribuyentesIndexRoute = AppContribuyentesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppContribuyentesRoute,
} as any)
const AppNotificacionesIdRoute = AppNotificacionesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppNotificacionesRoute,
} as any)
const AppFormulariosIdRoute = AppFormulariosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppFormulariosRoute,
} as any)
const AppContribuyentesIdRoute = AppContribuyentesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppContribuyentesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auditoria': typeof AppAuditoriaRoute
  '/contribuyentes': typeof AppContribuyentesRouteWithChildren
  '/formularios': typeof AppFormulariosRouteWithChildren
  '/mapa': typeof AppMapaRoute
  '/notificaciones': typeof AppNotificacionesRouteWithChildren
  '/perfil': typeof AppPerfilRoute
  '/reportes': typeof AppReportesRoute
  '/usuarios': typeof AppUsuariosRoute
  '/contribuyentes/$id': typeof AppContribuyentesIdRoute
  '/formularios/$id': typeof AppFormulariosIdRoute
  '/notificaciones/$id': typeof AppNotificacionesIdRoute
  '/contribuyentes/': typeof AppContribuyentesIndexRoute
  '/formularios/': typeof AppFormulariosIndexRoute
  '/notificaciones/': typeof AppNotificacionesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auditoria': typeof AppAuditoriaRoute
  '/mapa': typeof AppMapaRoute
  '/perfil': typeof AppPerfilRoute
  '/reportes': typeof AppReportesRoute
  '/usuarios': typeof AppUsuariosRoute
  '/contribuyentes/$id': typeof AppContribuyentesIdRoute
  '/formularios/$id': typeof AppFormulariosIdRoute
  '/notificaciones/$id': typeof AppNotificacionesIdRoute
  '/contribuyentes': typeof AppContribuyentesIndexRoute
  '/formularios': typeof AppFormulariosIndexRoute
  '/notificaciones': typeof AppNotificacionesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/auditoria': typeof AppAuditoriaRoute
  '/_app/contribuyentes': typeof AppContribuyentesRouteWithChildren
  '/_app/formularios': typeof AppFormulariosRouteWithChildren
  '/_app/mapa': typeof AppMapaRoute
  '/_app/notificaciones': typeof AppNotificacionesRouteWithChildren
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/reportes': typeof AppReportesRoute
  '/_app/usuarios': typeof AppUsuariosRoute
  '/_app/contribuyentes/$id': typeof AppContribuyentesIdRoute
  '/_app/formularios/$id': typeof AppFormulariosIdRoute
  '/_app/notificaciones/$id': typeof AppNotificacionesIdRoute
  '/_app/contribuyentes/': typeof AppContribuyentesIndexRoute
  '/_app/formularios/': typeof AppFormulariosIndexRoute
  '/_app/notificaciones/': typeof AppNotificacionesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/sitemap.xml'
    | '/auditoria'
    | '/contribuyentes'
    | '/formularios'
    | '/mapa'
    | '/notificaciones'
    | '/perfil'
    | '/reportes'
    | '/usuarios'
    | '/contribuyentes/$id'
    | '/formularios/$id'
    | '/notificaciones/$id'
    | '/contribuyentes/'
    | '/formularios/'
    | '/notificaciones/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sitemap.xml'
    | '/auditoria'
    | '/mapa'
    | '/perfil'
    | '/reportes'
    | '/usuarios'
    | '/contribuyentes/$id'
    | '/formularios/$id'
    | '/notificaciones/$id'
    | '/contribuyentes'
    | '/formularios'
    | '/notificaciones'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/sitemap.xml'
    | '/_app/auditoria'
    | '/_app/contribuyentes'
    | '/_app/formularios'
    | '/_app/mapa'
    | '/_app/notificaciones'
    | '/_app/perfil'
    | '/_app/reportes'
    | '/_app/usuarios'
    | '/_app/contribuyentes/$id'
    | '/_app/formularios/$id'
    | '/_app/notificaciones/$id'
    | '/_app/contribuyentes/'
    | '/_app/formularios/'
    | '/_app/notificaciones/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/usuarios': {
      id: '/_app/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reportes': {
      id: '/_app/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof AppReportesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notificaciones': {
      id: '/_app/notificaciones'
      path: '/notificaciones'
      fullPath: '/notificaciones'
      preLoaderRoute: typeof AppNotificacionesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mapa': {
      id: '/_app/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof AppMapaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/formularios': {
      id: '/_app/formularios'
      path: '/formularios'
      fullPath: '/formularios'
      preLoaderRoute: typeof AppFormulariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contribuyentes': {
      id: '/_app/contribuyentes'
      path: '/contribuyentes'
      fullPath: '/contribuyentes'
      preLoaderRoute: typeof AppContribuyentesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auditoria': {
      id: '/_app/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AppAuditoriaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notificaciones/': {
      id: '/_app/notificaciones/'
      path: '/'
      fullPath: '/notificaciones/'
      preLoaderRoute: typeof AppNotificacionesIndexRouteImport
      parentRoute: typeof AppNotificacionesRoute
    }
    '/_app/formularios/': {
      id: '/_app/formularios/'
      path: '/'
      fullPath: '/formularios/'
      preLoaderRoute: typeof AppFormulariosIndexRouteImport
      parentRoute: typeof AppFormulariosRoute
    }
    '/_app/contribuyentes/': {
      id: '/_app/contribuyentes/'
      path: '/'
      fullPath: '/contribuyentes/'
      preLoaderRoute: typeof AppContribuyentesIndexRouteImport
      parentRoute: typeof AppContribuyentesRoute
    }
    '/_app/notificaciones/$id': {
      id: '/_app/notificaciones/$id'
      path: '/$id'
      fullPath: '/notificaciones/$id'
      preLoaderRoute: typeof AppNotificacionesIdRouteImport
      parentRoute: typeof AppNotificacionesRoute
    }
    '/_app/formularios/$id': {
      id: '/_app/formularios/$id'
      path: '/$id'
      fullPath: '/formularios/$id'
      preLoaderRoute: typeof AppFormulariosIdRouteImport
      parentRoute: typeof AppFormulariosRoute
    }
    '/_app/contribuyentes/$id': {
      id: '/_app/contribuyentes/$id'
      path: '/$id'
      fullPath: '/contribuyentes/$id'
      preLoaderRoute: typeof AppContribuyentesIdRouteImport
      parentRoute: typeof AppContribuyentesRoute
    }
  }
}

interface AppContribuyentesRouteChildren {
  AppContribuyentesIdRoute: typeof AppContribuyentesIdRoute
  AppContribuyentesIndexRoute: typeof AppContribuyentesIndexRoute
}

const AppContribuyentesRouteChildren: AppContribuyentesRouteChildren = {
  AppContribuyentesIdRoute: AppContribuyentesIdRoute,
  AppContribuyentesIndexRoute: AppContribuyentesIndexRoute,
}

const AppContribuyentesRouteWithChildren =
  AppContribuyentesRoute._addFileChildren(AppContribuyentesRouteChildren)

interface AppFormulariosRouteChildren {
  AppFormulariosIdRoute: typeof AppFormulariosIdRoute
  AppFormulariosIndexRoute: typeof AppFormulariosIndexRoute
}

const AppFormulariosRouteChildren: AppFormulariosRouteChildren = {
  AppFormulariosIdRoute: AppFormulariosIdRoute,
  AppFormulariosIndexRoute: AppFormulariosIndexRoute,
}

const AppFormulariosRouteWithChildren = AppFormulariosRoute._addFileChildren(
  AppFormulariosRouteChildren,
)

interface AppNotificacionesRouteChildren {
  AppNotificacionesIdRoute: typeof AppNotificacionesIdRoute
  AppNotificacionesIndexRoute: typeof AppNotificacionesIndexRoute
}

const AppNotificacionesRouteChildren: AppNotificacionesRouteChildren = {
  AppNotificacionesIdRoute: AppNotificacionesIdRoute,
  AppNotificacionesIndexRoute: AppNotificacionesIndexRoute,
}

const AppNotificacionesRouteWithChildren =
  AppNotificacionesRoute._addFileChildren(AppNotificacionesRouteChildren)

interface AppRouteChildren {
  AppAuditoriaRoute: typeof AppAuditoriaRoute
  AppContribuyentesRoute: typeof AppContribuyentesRouteWithChildren
  AppFormulariosRoute: typeof AppFormulariosRouteWithChildren
  AppMapaRoute: typeof AppMapaRoute
  AppNotificacionesRoute: typeof AppNotificacionesRouteWithChildren
  AppPerfilRoute: typeof AppPerfilRoute
  AppReportesRoute: typeof AppReportesRoute
  AppUsuariosRoute: typeof AppUsuariosRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditoriaRoute: AppAuditoriaRoute,
  AppContribuyentesRoute: AppContribuyentesRouteWithChildren,
  AppFormulariosRoute: AppFormulariosRouteWithChildren,
  AppMapaRoute: AppMapaRoute,
  AppNotificacionesRoute: AppNotificacionesRouteWithChildren,
  AppPerfilRoute: AppPerfilRoute,
  AppReportesRoute: AppReportesRoute,
  AppUsuariosRoute: AppUsuariosRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
