/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerificacionIdRouteImport } from './routes/verificacion.$id'
import { Route as VerificacionFormularioIdRouteImport } from './routes/verificacion-formulario.$id'
import { Route as VNotificacionRouteImport } from './routes/v.notificacion'
import { Route as AppZonasRouteImport } from './routes/_app.zonas'
import { Route as AppUsuariosRouteImport } from './routes/_app.usuarios'
import { Route as AppTiposTramiteRouteImport } from './routes/_app.tipos-tramite'
import { Route as AppReportesRouteImport } from './routes/_app.reportes'
import { Route as AppPerfilRouteImport } from './routes/_app.perfil'
import { Route as AppNotificacionesRouteImport } from './routes/_app.notificaciones'
import { Route as AppMapaRouteImport } from './routes/_app.mapa'
import { Route as AppFormulariosRouteImport } from './routes/_app.formularios'
import { Route as AppContribuyentesRouteImport } from './routes/_app.contribuyentes'
import { Route as AppTiposTramiteIndexRouteImport } from './routes/_app.tipos-tramite.index'
import { Route as AppNotificacionesIndexRouteImport } from './routes/_app.notificaciones.index'
import { Route as AppFormulariosIndexRouteImport } from './routes/_app.formularios.index'
import { Route as AppContribuyentesIndexRouteImport } from './routes/_app.contribuyentes.index'
import { Route as VerificacionIdPdfRouteImport } from './routes/verificacion.$id.pdf'
import { Route as AppNotificacionesIdRouteImport } from './routes/_app.notificaciones.$id'
import { Route as AppFormulariosIdRouteImport } from './routes/_app.formularios.$id'
import { Route as AppContribuyentesIdRouteImport } from './routes/_app.contribuyentes.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificacionIdRoute = VerificacionIdRouteImport.update({
  id: '/verificacion/$id',
  path: '/verificacion/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificacionFormularioIdRoute =
  VerificacionFormularioIdRouteImport.update({
    id: '/verificacion-formulario/$id',
    path: '/verificacion-formulario/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const VNotificacionRoute = VNotificacionRouteImport.update({
  id: '/v/notificacion',
  path: '/v/notificacion',
  getParentRoute: () => rootRouteImport,
} as any)
const AppZonasRoute = AppZonasRouteImport.update({
  id: '/zonas',
  path: '/zonas',
  getParentRoute: () => AppRoute,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppTiposTramiteRoute = AppTiposTramiteRouteImport.update({
  id: '/tipos-tramite',
  path: '/tipos-tramite',
  getParentRoute: () => AppRoute,
} as any)
const AppReportesRoute = AppReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificacionesRoute = AppNotificacionesRouteImport.update({
  id: '/notificaciones',
  path: '/notificaciones',
  getParentRoute: () => AppRoute,
} as any)
const AppMapaRoute = AppMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => AppRoute,
} as any)
const AppFormulariosRoute = AppFormulariosRouteImport.update({
  id: '/formularios',
  path: '/formularios',
  getParentRoute: () => AppRoute,
} as any)
const AppContribuyentesRoute = AppContribuyentesRouteImport.update({
  id: '/contribuyentes',
  path: '/contribuyentes',
  getParentRoute: () => AppRoute,
} as any)
const AppTiposTramiteIndexRoute = AppTiposTramiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTiposTramiteRoute,
} as any)
const AppNotificacionesIndexRoute = AppNotificacionesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppNotificacionesRoute,
} as any)
const AppFormulariosIndexRoute = AppFormulariosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppFormulariosRoute,
} as any)
const AppContribuyentesIndexRoute = AppContribuyentesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppContribuyentesRoute,
} as any)
const VerificacionIdPdfRoute = VerificacionIdPdfRouteImport.update({
  id: '/pdf',
  path: '/pdf',
  getParentRoute: () => VerificacionIdRoute,
} as any)
const AppNotificacionesIdRoute = AppNotificacionesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppNotificacionesRoute,
} as any)
const AppFormulariosIdRoute = AppFormulariosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppFormulariosRoute,
} as any)
const AppContribuyentesIdRoute = AppContribuyentesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppContribuyentesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/contribuyentes': typeof AppContribuyentesRouteWithChildren
  '/formularios': typeof AppFormulariosRouteWithChildren
  '/mapa': typeof AppMapaRoute
  '/notificaciones': typeof AppNotificacionesRouteWithChildren
  '/perfil': typeof AppPerfilRoute
  '/reportes': typeof AppReportesRoute
  '/tipos-tramite': typeof AppTiposTramiteRouteWithChildren
  '/usuarios': typeof AppUsuariosRoute
  '/zonas': typeof AppZonasRoute
  '/v/notificacion': typeof VNotificacionRoute
  '/verificacion-formulario/$id': typeof VerificacionFormularioIdRoute
  '/verificacion/$id': typeof VerificacionIdRouteWithChildren
  '/contribuyentes/$id': typeof AppContribuyentesIdRoute
  '/formularios/$id': typeof AppFormulariosIdRoute
  '/notificaciones/$id': typeof AppNotificacionesIdRoute
  '/verificacion/$id/pdf': typeof VerificacionIdPdfRoute
  '/contribuyentes/': typeof AppContribuyentesIndexRoute
  '/formularios/': typeof AppFormulariosIndexRoute
  '/notificaciones/': typeof AppNotificacionesIndexRoute
  '/tipos-tramite/': typeof AppTiposTramiteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/mapa': typeof AppMapaRoute
  '/perfil': typeof AppPerfilRoute
  '/reportes': typeof AppReportesRoute
  '/usuarios': typeof AppUsuariosRoute
  '/zonas': typeof AppZonasRoute
  '/v/notificacion': typeof VNotificacionRoute
  '/verificacion-formulario/$id': typeof VerificacionFormularioIdRoute
  '/verificacion/$id': typeof VerificacionIdRouteWithChildren
  '/contribuyentes/$id': typeof AppContribuyentesIdRoute
  '/formularios/$id': typeof AppFormulariosIdRoute
  '/notificaciones/$id': typeof AppNotificacionesIdRoute
  '/verificacion/$id/pdf': typeof VerificacionIdPdfRoute
  '/contribuyentes': typeof AppContribuyentesIndexRoute
  '/formularios': typeof AppFormulariosIndexRoute
  '/notificaciones': typeof AppNotificacionesIndexRoute
  '/tipos-tramite': typeof AppTiposTramiteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/contribuyentes': typeof AppContribuyentesRouteWithChildren
  '/_app/formularios': typeof AppFormulariosRouteWithChildren
  '/_app/mapa': typeof AppMapaRoute
  '/_app/notificaciones': typeof AppNotificacionesRouteWithChildren
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/reportes': typeof AppReportesRoute
  '/_app/tipos-tramite': typeof AppTiposTramiteRouteWithChildren
  '/_app/usuarios': typeof AppUsuariosRoute
  '/_app/zonas': typeof AppZonasRoute
  '/v/notificacion': typeof VNotificacionRoute
  '/verificacion-formulario/$id': typeof VerificacionFormularioIdRoute
  '/verificacion/$id': typeof VerificacionIdRouteWithChildren
  '/_app/contribuyentes/$id': typeof AppContribuyentesIdRoute
  '/_app/formularios/$id': typeof AppFormulariosIdRoute
  '/_app/notificaciones/$id': typeof AppNotificacionesIdRoute
  '/verificacion/$id/pdf': typeof VerificacionIdPdfRoute
  '/_app/contribuyentes/': typeof AppContribuyentesIndexRoute
  '/_app/formularios/': typeof AppFormulariosIndexRoute
  '/_app/notificaciones/': typeof AppNotificacionesIndexRoute
  '/_app/tipos-tramite/': typeof AppTiposTramiteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/sitemap.xml'
    | '/contribuyentes'
    | '/formularios'
    | '/mapa'
    | '/notificaciones'
    | '/perfil'
    | '/reportes'
    | '/tipos-tramite'
    | '/usuarios'
    | '/zonas'
    | '/v/notificacion'
    | '/verificacion-formulario/$id'
    | '/verificacion/$id'
    | '/contribuyentes/$id'
    | '/formularios/$id'
    | '/notificaciones/$id'
    | '/verificacion/$id/pdf'
    | '/contribuyentes/'
    | '/formularios/'
    | '/notificaciones/'
    | '/tipos-tramite/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sitemap.xml'
    | '/mapa'
    | '/perfil'
    | '/reportes'
    | '/usuarios'
    | '/zonas'
    | '/v/notificacion'
    | '/verificacion-formulario/$id'
    | '/verificacion/$id'
    | '/contribuyentes/$id'
    | '/formularios/$id'
    | '/notificaciones/$id'
    | '/verificacion/$id/pdf'
    | '/contribuyentes'
    | '/formularios'
    | '/notificaciones'
    | '/tipos-tramite'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/sitemap.xml'
    | '/_app/contribuyentes'
    | '/_app/formularios'
    | '/_app/mapa'
    | '/_app/notificaciones'
    | '/_app/perfil'
    | '/_app/reportes'
    | '/_app/tipos-tramite'
    | '/_app/usuarios'
    | '/_app/zonas'
    | '/v/notificacion'
    | '/verificacion-formulario/$id'
    | '/verificacion/$id'
    | '/_app/contribuyentes/$id'
    | '/_app/formularios/$id'
    | '/_app/notificaciones/$id'
    | '/verificacion/$id/pdf'
    | '/_app/contribuyentes/'
    | '/_app/formularios/'
    | '/_app/notificaciones/'
    | '/_app/tipos-tramite/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VNotificacionRoute: typeof VNotificacionRoute
  VerificacionFormularioIdRoute: typeof VerificacionFormularioIdRoute
  VerificacionIdRoute: typeof VerificacionIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verificacion/$id': {
      id: '/verificacion/$id'
      path: '/verificacion/$id'
      fullPath: '/verificacion/$id'
      preLoaderRoute: typeof VerificacionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verificacion-formulario/$id': {
      id: '/verificacion-formulario/$id'
      path: '/verificacion-formulario/$id'
      fullPath: '/verificacion-formulario/$id'
      preLoaderRoute: typeof VerificacionFormularioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/notificacion': {
      id: '/v/notificacion'
      path: '/v/notificacion'
      fullPath: '/v/notificacion'
      preLoaderRoute: typeof VNotificacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/zonas': {
      id: '/_app/zonas'
      path: '/zonas'
      fullPath: '/zonas'
      preLoaderRoute: typeof AppZonasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/usuarios': {
      id: '/_app/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tipos-tramite': {
      id: '/_app/tipos-tramite'
      path: '/tipos-tramite'
      fullPath: '/tipos-tramite'
      preLoaderRoute: typeof AppTiposTramiteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reportes': {
      id: '/_app/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof AppReportesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notificaciones': {
      id: '/_app/notificaciones'
      path: '/notificaciones'
      fullPath: '/notificaciones'
      preLoaderRoute: typeof AppNotificacionesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mapa': {
      id: '/_app/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof AppMapaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/formularios': {
      id: '/_app/formularios'
      path: '/formularios'
      fullPath: '/formularios'
      preLoaderRoute: typeof AppFormulariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contribuyentes': {
      id: '/_app/contribuyentes'
      path: '/contribuyentes'
      fullPath: '/contribuyentes'
      preLoaderRoute: typeof AppContribuyentesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tipos-tramite/': {
      id: '/_app/tipos-tramite/'
      path: '/'
      fullPath: '/tipos-tramite/'
      preLoaderRoute: typeof AppTiposTramiteIndexRouteImport
      parentRoute: typeof AppTiposTramiteRoute
    }
    '/_app/notificaciones/': {
      id: '/_app/notificaciones/'
      path: '/'
      fullPath: '/notificaciones/'
      preLoaderRoute: typeof AppNotificacionesIndexRouteImport
      parentRoute: typeof AppNotificacionesRoute
    }
    '/_app/formularios/': {
      id: '/_app/formularios/'
      path: '/'
      fullPath: '/formularios/'
      preLoaderRoute: typeof AppFormulariosIndexRouteImport
      parentRoute: typeof AppFormulariosRoute
    }
    '/_app/contribuyentes/': {
      id: '/_app/contribuyentes/'
      path: '/'
      fullPath: '/contribuyentes/'
      preLoaderRoute: typeof AppContribuyentesIndexRouteImport
      parentRoute: typeof AppContribuyentesRoute
    }
    '/verificacion/$id/pdf': {
      id: '/verificacion/$id/pdf'
      path: '/pdf'
      fullPath: '/verificacion/$id/pdf'
      preLoaderRoute: typeof VerificacionIdPdfRouteImport
      parentRoute: typeof VerificacionIdRoute
    }
    '/_app/notificaciones/$id': {
      id: '/_app/notificaciones/$id'
      path: '/$id'
      fullPath: '/notificaciones/$id'
      preLoaderRoute: typeof AppNotificacionesIdRouteImport
      parentRoute: typeof AppNotificacionesRoute
    }
    '/_app/formularios/$id': {
      id: '/_app/formularios/$id'
      path: '/$id'
      fullPath: '/formularios/$id'
      preLoaderRoute: typeof AppFormulariosIdRouteImport
      parentRoute: typeof AppFormulariosRoute
    }
    '/_app/contribuyentes/$id': {
      id: '/_app/contribuyentes/$id'
      path: '/$id'
      fullPath: '/contribuyentes/$id'
      preLoaderRoute: typeof AppContribuyentesIdRouteImport
      parentRoute: typeof AppContribuyentesRoute
    }
  }
}

interface AppContribuyentesRouteChildren {
  AppContribuyentesIdRoute: typeof AppContribuyentesIdRoute
  AppContribuyentesIndexRoute: typeof AppContribuyentesIndexRoute
}

const AppContribuyentesRouteChildren: AppContribuyentesRouteChildren = {
  AppContribuyentesIdRoute: AppContribuyentesIdRoute,
  AppContribuyentesIndexRoute: AppContribuyentesIndexRoute,
}

const AppContribuyentesRouteWithChildren =
  AppContribuyentesRoute._addFileChildren(AppContribuyentesRouteChildren)

interface AppFormulariosRouteChildren {
  AppFormulariosIdRoute: typeof AppFormulariosIdRoute
  AppFormulariosIndexRoute: typeof AppFormulariosIndexRoute
}

const AppFormulariosRouteChildren: AppFormulariosRouteChildren = {
  AppFormulariosIdRoute: AppFormulariosIdRoute,
  AppFormulariosIndexRoute: AppFormulariosIndexRoute,
}

const AppFormulariosRouteWithChildren = AppFormulariosRoute._addFileChildren(
  AppFormulariosRouteChildren,
)

interface AppNotificacionesRouteChildren {
  AppNotificacionesIdRoute: typeof AppNotificacionesIdRoute
  AppNotificacionesIndexRoute: typeof AppNotificacionesIndexRoute
}

const AppNotificacionesRouteChildren: AppNotificacionesRouteChildren = {
  AppNotificacionesIdRoute: AppNotificacionesIdRoute,
  AppNotificacionesIndexRoute: AppNotificacionesIndexRoute,
}

const AppNotificacionesRouteWithChildren =
  AppNotificacionesRoute._addFileChildren(AppNotificacionesRouteChildren)

interface AppTiposTramiteRouteChildren {
  AppTiposTramiteIndexRoute: typeof AppTiposTramiteIndexRoute
}

const AppTiposTramiteRouteChildren: AppTiposTramiteRouteChildren = {
  AppTiposTramiteIndexRoute: AppTiposTramiteIndexRoute,
}

const AppTiposTramiteRouteWithChildren = AppTiposTramiteRoute._addFileChildren(
  AppTiposTramiteRouteChildren,
)

interface AppRouteChildren {
  AppContribuyentesRoute: typeof AppContribuyentesRouteWithChildren
  AppFormulariosRoute: typeof AppFormulariosRouteWithChildren
  AppMapaRoute: typeof AppMapaRoute
  AppNotificacionesRoute: typeof AppNotificacionesRouteWithChildren
  AppPerfilRoute: typeof AppPerfilRoute
  AppReportesRoute: typeof AppReportesRoute
  AppTiposTramiteRoute: typeof AppTiposTramiteRouteWithChildren
  AppUsuariosRoute: typeof AppUsuariosRoute
  AppZonasRoute: typeof AppZonasRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppContribuyentesRoute: AppContribuyentesRouteWithChildren,
  AppFormulariosRoute: AppFormulariosRouteWithChildren,
  AppMapaRoute: AppMapaRoute,
  AppNotificacionesRoute: AppNotificacionesRouteWithChildren,
  AppPerfilRoute: AppPerfilRoute,
  AppReportesRoute: AppReportesRoute,
  AppTiposTramiteRoute: AppTiposTramiteRouteWithChildren,
  AppUsuariosRoute: AppUsuariosRoute,
  AppZonasRoute: AppZonasRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface VerificacionIdRouteChildren {
  VerificacionIdPdfRoute: typeof VerificacionIdPdfRoute
}

const VerificacionIdRouteChildren: VerificacionIdRouteChildren = {
  VerificacionIdPdfRoute: VerificacionIdPdfRoute,
}

const VerificacionIdRouteWithChildren = VerificacionIdRoute._addFileChildren(
  VerificacionIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VNotificacionRoute: VNotificacionRoute,
  VerificacionFormularioIdRoute: VerificacionFormularioIdRoute,
  VerificacionIdRoute: VerificacionIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
